### Table 1
data <- read.csv("~/G_ripple_data14.csv")
library(plm)
lm1<-lm(delta_C_ITE~group+award_prestige+delta_T+genderLabel+Award_age+award_year+discipline, data = data)
summary(lm1)
lm2 <- lm(delta_C_ITE ~ group+award_prestige+award_year+discipline, data = data)
summary(lm2)
lm3 <- lm(delta_C_ITE ~ group+award_prestige+group*award_prestige+award_year+discipline, data = data)
summary(lm3)
lm4 <- plm(delta_C_ITE ~ group+delta_T+award_year+discipline, data = data, effect = "individual", model = "within", index = "Winner_ID")
summary(lm4)
lm5 <- plm(delta_C_ITE ~ group+delta_T+group*delta_T+award_year+discipline, data = data, effect = "individual", model = "within", index = "Winner_ID")
summary(lm5)
lm6 <- lm(delta_C_ITE ~ group+genderLabel+award_year+discipline, data = data)
summary(lm6)
lm7 <- lm(delta_C_ITE ~ group+genderLabel+group*genderLabel+award_year+discipline, data = data)
summary(lm7)
lm8 <- lm(delta_C_ITE ~ group+Award_age+award_year+discipline, data = data)
summary(lm8)
lm9 <- lm(delta_C_ITE ~ group+Award_age+group*Award_age+award_year+discipline, data = data)
summary(lm9)
### Table 2 Mediation Effect
data1 <- read.csv("~/G_ripple_data15.csv")
lm1 <- plm(delta_C_M ~ treated_paper+award_prestige+award_year+genderLabel+Award_age, data = data1, effect = "individual", model = "within", index = "WinnerID")
summary(lm1)
lm2 <- plm(delta_C_Y ~ treated_paper+award_prestige+award_year+genderLabel+Award_age, data = data1, effect = "individual", model = "within", index = "WinnerID")
summary(lm2)
lm3 <- plm(delta_C_Y ~ treated_paper+delta_C_M+award_prestige+award_year+genderLabel+Award_age, data = data1, effect = "individual", model = "within", index = "WinnerID")
summary(lm3)